- setup.py
`pip >= 6` introduced `session` as a required argument for `parse_requirements`
Added a `session` to the call.
See the tests pass.
> Fix for pip>=6

- docs/index.rst
I updated the documentation for the validate_api_call method. Basically I changed the name of the parameters.
In this [commit](https://github.com/pipermerriam/flex/commit/6dd40bf9ce451b2e48565432acb0a32e79c0afc0#diff-f3a867d094642f074d48613d6330c28f) the validate_api_call was changed:
```ssh
-def validate_api_call(schema, request, response):
+def validate_api_call(schema, raw_request, raw_response):
```
So I updated the documentation.
> #45 - Updating documentation for validate_api_call

- flex/paths.py
Fixed little typo in the file paths.py:
```ssh
-        raise LookupError('Multipue paths found for {0}.  Found `{1}`'.format(
+        raise LookupError('Multiple paths found for {0}.  Found `{1}`'.format(
```
Sorry, I forgot the **cute animal**:
> Fixing typo in paths.py

- flex/paths.py
- tests/core/test_match_request_path_to_api_path.py
`flex.paths.match_path_to_api_path` was looking at the global parameter definitions and the path level parameter definitions, but not at the operation level parameter definitions.
Adjusted the function to extract and use the parameter definitions from the operations under the path.
`tests.core.test_match_request_path_to_api_path.py::test_match_path_with_parameter_defined_in_operation`
Also try to match `/pets/dog` against the following schema and see it matches.
```yaml
/v1/pets/{petId}:
get:
summary: Info for a specific pet
operationId: showPetById
tags:
- pets
parameters:
- name: petId
in: path
description: The id of the pet to retrieve
type: string
responses:
200:
description: Expected response to a valid request
schema:
$ref: Pets
default:
description: unexpected error
schema:
$ref: …
```
> Fixes #52 - path matching should look at operation parameters as well

- flex/error_messages.py
- flex/exceptions.py
- flex/paths.py
- flex/validation/common.py
- tests/core/test_match_request_path_to_api_path.py
- tests/validation/path/test_validate_path_to_api_path.py
- tests/validation/request/test_request_path_validation.py
- tests/validation/response/test_response_path_validation.py
- The function `flex.paths.match_path_to_api_path` considered multiple matches to be an error state.
- The error of no matches and multiple matches were not kept distinct so the error message was not helpful when multiple matches were found.
- Added logic for when multiple matches are found to try and pick the match with the highest number of matching groups.  This fixes what is probably the most common case for this code failing which is having a nested resource (very common).
- Added distinct error reporting for the two error cases.
Try to validate a request/schema combination like the one found in #56 
> Fixes #56 - handle multiple paths found a bit smarter

- flex/paths.py
- tests/core/test_match_request_path_to_api_path.py
* The function match_path_to_api_path in paths.py was giving an error. Because the [matches](https://github.com/pipermerriam/flex/blob/master/flex/paths.py#L156) variable was something like this:
```ssh
[('/v1/pets/', None),
('/v1/pets/{petId}', <_sre.SRE_Match object; span=(0, 52), match='/v1/pets/1/name/lucky>), 
('/v1/pets/{petId}/name/{namePet}', <_sre.SRE_Match object; span=(0, 52), match='/v1/pets/1/name/lucky>)]
```
So in this [line](https://github.com/pipermerriam/flex/blob/master/flex/paths.py#L159) gives the error **"AttributeError: 'NoneType' object has no attribute 'groups'"**.
Adding validation to see if the match is not None.
Here is a cute animal picture for your troubles...
> Adding validation to see if the match is not None

- flex/loading/common/schema/__init__.py
- flex/loading/common/schema/required.py
- flex/loading/common/single_header/__init__.py
- flex/loading/common/single_header/type.py
- flex/loading/common/single_parameter/__init__.py
- flex/loading/common/single_parameter/in_.py
- flex/loading/common/single_parameter/name.py
- flex/loading/definitions/responses/single/__init__.py
- flex/loading/schema/__init__.py
- flex/loading/schema/info.py
- flex/loading/schema/paths/__init__.py
- flex/loading/schema/paths/path_item/__init__.py
- flex/loading/schema/paths/path_item/operation/responses/single/__init__.py
- flex/loading/schema/swagger.py
- flex/validation/common.py
- flex/validation/parameter.py
- flex/validation/schema.py
- pytest.ini
- tests/loading/definition/responses/headers/single/test_type_validation.py
- tests/loading/definition/schema/test_required.py
- tests/loading/schema/test_info_validation.py
- tests/loading/schema/test_paths_validation.py
- tests/loading/schema/test_swagger_validation.py
- tests/validation/response/test_schema_validation.py
- tests/validation/schema/test_ref_validation.py
- tests/validation/schema/test_required_validation.py
Flex was expecting the following usage of the `required` keyword argument for schema objects.
```yaml
Pet:
properties:
id:
type: integer
required: true
format: int64
name:
type: string
required: true
```
Changed the handling to match the 
[json schema required spec](http://json-schema.org/latest/json-schema-validation.html#anchor61)
> The value of this keyword MUST be an array. This array MUST have at least one element. Elements of this array MUST be strings, and MUST be unique.
```yaml
Pet:
required:
- id
- name
properties:
id:
type: integer
format: int64
name:
type: string
```
See that usage of the `required` keyword as a list of field names validates correctly.
> Fixes #62 - Proper handling of required field on schema objects

- flex/paths.py
- tests/core/test_match_request_path_to_api_path.py
cc @alvarocavalcanti
Trying to match the path `/v1/accounts/23` against a schema with the following paths throws an error.
```
paths:
- "/v1/accounts/{account_id}"
- "/v1/accounts/{account_id}/subscriptions"
```
Changed the logic around picking from multiple matches to choose the longest api path.  This doesn't actually fix #58 but it still improves the situation.
Match the path `/v1/accounts/23` against a schema with the following paths and see that it matches the `/subscriptions` one correctly.
```
paths:
- "/v1/accounts/{account_id}"
- "/v1/accounts/{account_id}/subscriptions"
```
> Further improvements to path matching

- flex/http.py
- flex/validation/operation.py
- tests/core/test_example_schemas.py
- tests/core/test_format_validators.py
- tests/http/test_request_data_property.py
- tests/validation/request/test_request_body_parameter_validation.py
Stub.
will fix #9
> Body - The payload that's appended to the HTTP request. Since there can only be one payload, there can only be one body parameter. The name of the body parameter has no effect on the parameter itself and is used for documentation purposes only. Since Form parameters are also in the payload, body and form parameters cannot exist together for the same operation.
Not sure how much of this should be enforced by flex.
> Add request body parameter validation 

- flex/loading/common/single_parameter/__init__.py
- tests/loading/definition/parameters/single/test_default_validation.py
cc @MattiSG
The validator for the `default` keyword was being loaded onto the single parameter validator as a property validator rather than a field validator.  Since property validators try to pull a key off of an object, this threw an attribute error.
Fixed how the type validation for the default keyword was loaded onto the single parameter validation.
Try to validate the following schema.
```bash
$ flex --source http://openfisca.sgmap.fr/api/1/swagger
```
> Fixes #68 - default keyword was not loaded correctly

- flex/formats.py
- flex/loading/common/external_docs.py
- flex/loading/common/schema/__init__.py
- flex/loading/schema/paths/path_item/operation/__init__.py
- tests/loading/common/test_external_docs_validator.py
- tests/loading/schema/paths/operation/responses/schema/test_external_docs_validation.py
- tests/loading/schema/paths/operation/test_external_docs_validation.py
The validation of the `externalDocs` keyword was incorrectly validating it as a string rather than the [`ExternalDocs`](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#external-documentation-object)
Fixed it to be compliant with the swagger schema.
Validate a schema which declares external documentation objects.
> Fix external docs validation

- flex/error_messages.py
- flex/loading/definitions/__init__.py
- flex/loading/definitions/schema_definitions.py
- flex/loading/schema/paths/path_item/operation/responses/single/schema/ref.py
- flex/validation/schema.py
- requirements.txt
- tests/core/test_example_schemas.py
- tests/loading/definition/test_reference_validation.py
- tests/loading/schema/paths/operation/responses/schema/test_reference_validation.py
- tests/schemas/httpbin.yaml
- tests/validation/parameter/test_schema_validation.py
- tests/validation/response/test_schema_validation.py
- tests/validation/schema/test_items_validation.py
- tests/validation/schema/test_ref_validation.py
The way that `flex` validated and looked up `$ref` values was not compliant with the specification.
Switched to using the `jsonpointer` library to resolve `$ref` values.  The current implementation only supports local references.  Fetching remote references is something that needs to be done.
See that a schema with a json pointer style reference `#/definitions/SomeReference` will evaluate and validate correctly.
> Use appropriate RFC compliant json point resolution

- CHANGELOG
- flex/__init__.py
- setup.py
The use of pips internals to parse the requirements.txt file is problematic.
> Remove the use of pip's internals

- flex/exceptions.py
- flex/loading/common/reference.py
- flex/loading/schema/paths/path_item/__init__.py
- flex/loading/schema/paths/path_item/operation/responses/__init__.py
- flex/loading/schema/paths/path_item/parameters/__init__.py
- flex/loading/schema/paths/path_item/parameters/single.py
- flex/parameters.py
- flex/paths.py
- flex/utils.py
- flex/validation/common.py
- flex/validation/operation.py
- flex/validation/parameter.py
- flex/validation/reference.py
- flex/validation/request.py
- flex/validation/response.py
- flex/validation/schema.py
- flex/validation/utils.py
- tests/loading/common/test_reference_object_validation.py
- tests/loading/schema/paths/operation/responses/test_response_validation.py
- tests/utils.py
- tests/validation/path/test_validate_path_to_api_path.py
- tests/validation/request/test_request_body_parameter_validation.py
- tests/validation/request/test_request_path_validation.py
- tests/validation/request/test_request_query_parameter_validation.py
- tests/validation/response/test_response_path_validation.py
The handling of the swagger `responseObject` was wrong.  Basically, anything that allowed for either the local object or a ref object was validating the ref object as if it was the local object.
Fixed handling of ref objects.
Try to validate a path with a response that is a reference and see that it doesn't complain.
> ewwww this is really gross

- flex/error_messages.py
- flex/loading/common/schema/__init__.py
- flex/validation/schema.py
- tests/validation/schema/test_additional_properties_validation.py
No valdiation was being perform against the [`additionalProperties`](http://json-schema.org/latest/json-schema-validation.html#anchor64) schema keyword.
Added checking against the object keys to see if any additional properties are present whenever `additionalProperties` is Falsy
Issue #82 will be resolved
> Fixes #82 - Add additionalProperties validation

- docs/index.rst
- setup.py
Fixes #93
The command line interface for flex used the same executable as http://flex.sourceforge.net/.  This has cause some confusion and problems for people who use both tools.  Since the Apache project has been around for longer, it seems appropriate that this project to change the name of it's command line interface.
The CLI executable is being renamed to `swagger-flex`
> Change CLI tool to swagger-flex

- flex/paths.py
- tests/core/test_match_request_path_to_api_path.py
- tests/core/test_path_utils.py
This prevents a match of a template `/get/{username}/posts/{id}` to `/get/simon/posts/123/unread`, which I think is the correct behavior.
> don't allow parameters to expand across slashes

- flex/validation/response.py
- tests/validation/response/test_response_status_code_validation.py
See #96.¹
¹ see also [this cute picture of a hedgehog](https://s-media-cache-ak0.pinimg.com/564x/47/31/0e/47310ecbfc266abbea3db0cd626fd0dc.jpg).
> make use of a 'default' response [closes #96]

- flex/http.py
- tests/http/test_request_normalization.py
Apparently tornado uses a separate HTTPRequest in the server; who knew.
This adds support for it as well.
> add tornado httpserver.HTTPRequest support

- flex/core.py
I think this was the intended behavior, but I'm not entirely sure. The tests did pass, so if it's not it at least seems backwards compatible.
For context, our use case is schema generation from examples. To match and replace existing definitions, we're making a call like `validate(isolated_definition, example_body, context=schema)` for each existing definition, and generating a reference when validating succeeds. The context is needed for the case where isolated_definition references another definition.
And here's a [cute octopus](http://blogs.discovermagazine.com/d-brief/files/2015/06/octopus.jpg)!
> pass through kwargs to validate subcalls

- flex/paths.py
- tests/core/test_path_utils.py
- tests/validation/request/test_request_path_validation.py
- tests/validation/response/test_response_path_validation.py
This prevents matching a path like `/foo/bar` to a definition like `/foo/{id}` when id is an integer param.
Note that this is a breaking change if users were relying on the "got value of type..." message instead of "no paths found".
[also check out this kangaroo](http://justcuteanimals.com/wp-content/uploads/2014/11/Little-kangaroo-pictures-cute-animal-pics.jpg)
> generate path regexes with \d for integers [#58]

- flex/validation/common.py
- tests/validation/request/test_request_body_parameter_validation.py
- tests/validation/response/test_schema_validation.py
Swagger 2.0 does NOT support null in type array
(https://github.com/OAI/OpenAPI-Specification/issues/229). For now, using the
`x-nullable` extension is the best way.
Fixes pipermerriam/flex#91
> Adding NULL support

- flex/exceptions.py
- flex/parameters.py
- flex/validation/parameter.py
- tests/validation/request/test_request_header_validation.py
- tests/validation/request/test_request_parameter_validation.py
Typecast values passed in as query params since they are generally treated as strings.
Also, split arrays based on collection format
Fixes pipermerriam/flex#114
> Tyepcast query param parameters

- flex/functional.py
- flex/validation/operation.py
- flex/validation/response.py
The problem reported in #120 is reproducible under Python 2.7.12 which makes the bug slightly more serious. During validation `context` keyword argument is passed to `operator.attrgetter` and `operator.methodcaller` functions. It's not allowed by their signatures, but so far it was ignored due to a bug in Python (https://bugs.python.org/issue26822).
I took the laziest possible approach to fixing it - simply by bringing back former behavior to `attrgetter` and `methodcaller`.
> Fix "methodcaller does not take keyword arguments" error with Python 2.7.12

- .travis.yml
- flex/__init__.py
- requirements-dev.txt
- tox.ini
* No testing against python 3.5
* The falcon tests weren't actually being run due to travis ci file not being updated.
Changed the testing configurations
> Expand coverage to py35 and actually test the falcon stuff

- flex/http.py
- tests/http/test_request_data_property.py
Convert body to str when type is bytes to fix a problem in request validations in python 3.
> Convert body to str when type is bytes

- flex/constants.py
- flex/loading/common/single_header/type.py
- flex/loading/common/single_parameter/type.py
Add FILE to list of accepted types for parameter
Cherry-picking from #134 to latest in repo
This means we are attempting to address issue #122 as well.
> Add FILE type constant

- flex/paths.py
- tests/core/test_match_request_path_to_api_path.py
Fix issue #143 
Also included another fix in case the target path has multiple slashes (`http://localhost:8080/api/////test`), and it should match `/api/test`
> Fix base path being / and non-normalized target - Issue #143

- flex/http.py
- tests/http/test_request_normalization.py
- tests/http/test_response_normalization.py
- tox.ini
Add support for normalizing WebOb requests and responses. This lets us use the flex validator with the [WebTest functional testing framework](http://docs.pylonsproject.org/projects/webtest/en/latest/)
> Add webob normalization

- flex/validation/parameter.py
- tests/validation/request/test_request_path_validation.py
- tests/validation/response/test_response_path_validation.py
Fixed the incorrect response validation when `basePath` is present.
> Fix issue #152 - Fix the incorrect response validation

- README.md
pypip.in appears not to be functioning any more, sheilds.io provides
the same badges and is currently up.
> Replace pypip.in badges with shields.io badges

- flex/core.py
- tests/validation/api_call/test_api_call_validation.py
This is useful for situations where you might send a deliberately malformed request that doesn't match your Swagger specification but you want to test the error response does match.
Fixes https://github.com/pipermerriam/flex/issues/149
> Add a method for just validating the API response

- .travis.yml
- flex/http.py
- tests/http/test_request_normalization.py
- tests/http/test_response_normalization.py
- tox.ini
This adds django request/response normalization. I'd reckon there's still a little bit of work to be done here, e.g. documentation and perhaps rejigging the tox environments.  Also, I'm not sure how strict the django version should be or how that should be supported.
Happy to make any and all changes, I've raised as-is as it's working and I thought I there should be a discussion about the above points.
> Add django request/response normalization

- docs/index.rst
This should have been included in 075b7b32.
> Add django HttpRequest/HttpResponse to supported request/response docs

- flex/constants.py
- flex/error_messages.py
- flex/formats.py
- tests/validation/parameter/test_format_validation.py
- tests/validation/schema/test_format_validation.py
Swagger defines the date format, which are date (no time) strings
conforming to the full date format defined in RFC3339 (essentially
just the date portion of a full ISO8601 date/time). This adds
support for validation of this format.
> Add support for validation of dates

- flex/error_messages.py
- tests/cli/test_command_line_interface.py
Admittedly this is largely to do with preference, but I happened to notice it as the double space made me think that one of my JSON keys had a space as a prefix when I saw it in an error message:
Invalid value.  this_is_my_value is not one of the available options ('A', 'B')
Also the message for `HOST_MESSAGES['invalid']` does not have two spaces after full stops, so at the very least that should be made consistent with the others (by adding extra spaces there).
> Remove double space after full stop in error messages

- flex/error_messages.py
- flex/formats.py
- tests/core/test_format_validators.py
Hi!
The int32 and int64 formats seem to be validated in ranges different from the ranges of signed integer that is often used.  The int32 format is in the range from -4,294,967,295 to 4,294,967,295, and the int64 format is in the range from -18,446,744,073,709,551,615 to 18,446,744,073,709,551,615.
I'm not sure what the specification is saying.  But I hope these ranges will be changed so that it will be 32 bits or 64 bits including the bit necessary to express the sign.
If this request is merged, the int32 format will be in the range from -2,147,483,648 to 2,147,483,647 and the int64 format will be in the range from -9,223,372,036,854,775,808 to 9,223,372,036,854,775,807.
Thanks a lot.
Photo by [kristenadams](https://www.flickr.com/photos/kristenadams/3463566755/)
> Change the ranges of the int32 and int64 formats

- flex/error_messages.py
- flex/validation/common.py
- flex/validation/operation.py
- flex/validation/response.py
- tests/validation/request/test_request_content_type_validation.py
- tests/validation/response/test_response_content_type_validation.py
The Swagger specification says that consumes and produces are "A list
of MIME types...". The Content-Type header of a HTTP request consists
of a MIME type *and* optional parameters, e.g.
text/html; charset=utf-8
validation of request and response content type was failing when
parameters were present as the entire value of the Content-Type header
was compared to the allowed MIME types in consumes/produces.
This changes the validation of content types to only compare the MIME
type in the header to the allowed MIME types defined in consumes and
produces as appropriate for requests/responses.
> Fix parameters in content type causing validation failure

- flex/validation/common.py
- tests/validation/request/test_request_content_type_validation.py
- tests/validation/response/test_response_content_type_validation.py
This is the behaviour flex had prior to d91debaa, in that commit the
Content-Type validation logic was changed to assume the Content-Type
of a request was application/octet-stream if it was not otherwise
given. This is not wrong per se, but as the Content-Type header is
not given with requests with no body (e.g. a GET request) this meant
that these requests were considered to have the an invalid
Content-Type when they really, correctly had provided None. This
restores the previous behaviour where, in all cases, Content-Type
was would be ignored if not provided.
> Do not validate Content-Type if it is missing

- flex/core.py
da3ab9a3de0ef75e93a79f19efd013cfd11b2697 added the convenience method validate_api_response.  We tried using this new method in out existing django project. As the response validation needs a valid request path and django response don't know it we raise an exception if no path could be found ([http.py:L303](https://github.com/pipermerriam/flex/blob/master/flex/http.py#L303)).
Problem for us is that we can not use the convenience method as we have to supply an additional request for response validation and the method dows not allow to set a request. So I added an optional `raw_request` param which will be normalized and added to the response normalizer.
> Add optional raw_request param to validate_api_response

- flex/http.py
- tests/http/test_request_data_property.py
- tests/http/test_response_data_propery.py
Python's inbuilt json module is used to parse JSON in requests and
responses before it's checked against the schema. In Python 2 the
json module only raises ValueError in cases where it is unable to
parse the data, e.g.
import json
json.loads('{"not valid": [1,]}')
>>> ValueError: No JSON object could be decoded
whereas in Python 3 a JSONDecodeError is raised instead:
import json
json.loads('{"not valid": [1,]}')
>>> JSONDecodeError: Expecting value: line 1 column 18 (char 17)
In either Python version flex allows the exception to bubble, this
makes it difficult to determine programmatically that the JSON is
invalid in Python 2 (unless you examine the message or stack trace)
as ValueError can be raised in many situations.
This adds a custom JSONDecodeError in flex.http when run with Python …
> Raise flex.http.JSONDecodeEror when Request/Response JSON invalid

- flex/validation/response.py
- tests/validation/response/test_response_reference.py
Flex seems to ignore referenced response definitions when validating responses.
This fix properly dereference the response definition before response validation is performed.
> Fix response reference

- docs/index.rst
- flex/error_messages.py
- flex/formats.py
- requirements.txt
- setup.py
- tests/core/test_format_validators.py
- tests/validation/schema/test_format_validation.py
The Swagger spec states that date/times must be in the format described
by RFC3339, this a strict subset of the ISO8601 format, essentially
requiring that date/times are of the form:
2017-01-02T12:34:56Z
or
2017-01-02T12:34:56+00:00
(with microseconds allowed but optional).
Previously flex validated date/times against ISO8601, this is more
permissive than RFC3339 and so some date/time strings were considered
valid as they were valid ISO8601 date/times but were not valid
against RFC3339.
This changes date/time validation to check against the format specified
in RFC3339.
> Validate date/times are RFC3339 compliant

- flex/http.py
- tests/http/test_request_data_property.py
- tests/http/test_response_data_propery.py
HTTP POST/PUT requests SHOULD include a Content-Type but they don't
have to, if flex tried to validate a request without a Content-Type
an AttributeError would be raised as the data property of Request
and Response checks the content_type with .startswith to see if
it's JSON (and so should be parsed before further processing). This
exception happened before any validation on Content-Type so if you
have a schema with an endpoint that consumes application/json but
you validate a request without any Content-Type you ended up with
this exception instead of some validation error.
This puts a simple guard before the .startswith call preventing the
AttributeError.
> Avoid AttributeError on request/response data when Content-Type missing

- .travis.yml
- flex/core.py
- flex/loading/schema/host.py
- flex/loading/schema/paths/__init__.py
- flex/validation/common.py
- flex/validation/operation.py
- flex/validation/parameter.py
- flex/validation/request.py
- flex/validation/response.py
- tests/core/test_utils.py
There are two deprecated APIs:
* https://github.com/pipermerriam/flex/blob/master/flex/context_managers.py#L9
* https://github.com/pipermerriam/flex/blob/master/flex/utils.py#L29
but flex code itself haven't been fully migrated.
> Get rid of deprecation warnings

- Makefile
- flex/validation/common.py
- tests/validation/request/test_request_query_parameter_validation.py
1.  when a query parameter defined as an array with collection format: multi and it's value contains only one item, the only item will be split into a list with each charactor as an item. see the test case i added.
2.  the help message in Makefile contains a "testall" command, but actually it should be "test-all"
> fix error when query parameter defined as a Multi-CollectionFormat-Array, fix typo in Makefile

- flex/http.py
Request header validation always fails if running "validate_api_call" with a requests request. This is because request headers are not passed along in the normalize method.
> Pass on request headers when normalizing a requests request

- flex/http.py
- tests/http/test_request_normalization.py
- tests/http/test_response_normalization.py
Also add a test for requests without Content-Type (behavior was
already correct).
Fixes: https://github.com/pipermerriam/flex/issues/195
> Fix Django response normalization failing when no Content-Type

- flex/http.py
werkzeug.local is only created on-demand, so it may not yet exist when we try to use it.
The bug can be triggered like this (assuming a fresh Python interpreter):
```
from flex.core import load, validate_api_call
schema = load("https://raw.githubusercontent.com"
"/OAI/OpenAPI-Specification/master/examples/v2.0/json/petstore.json")
validate_api_call(schema, raw_request={}, raw_response={})
```
This produces `AttributeError: module 'werkzeug' has no attribute 'local'` due to the following behaviour of werkzeug:
```
>>> import werkzeug
>>> werkzeug.local
Traceback (most recent call last):
...
AttributeError: module 'werkzeug' has no attribute 'local'
>>> from werkzeug import local
>>> werkzeug.local
<module 'werkzeug.local'....>
```
> Ensure that werkzeug.local exists

- flex/core.py
- flex/validation/common.py
- tests/core/test_load_source.py
- tests/validation/schema/test_allof_validation.py
This PR
- adds a (previously failing) unit test for #146
- reverts generate_allof_validator to its original state for correct validation
- remove the discriminator key if discriminator is resolved to stop infinite recursion
Fixes #146
> Fix allOf validation #146

- flex/constants.py
- flex/validation/common.py
- tests/utils.py
- tests/validation/parameter/test_enum_validation.py
I've noticed that enums don't work very well with x-nullable=True. I had to include null/None as an enum value for the validation to pass, but that combo of x-nullable and enum value does not work with swagger-ui. 
So I suggest this change.
> Handle x nullable for enums

- flex/validation/common.py
#191 introduced support for `None` in enums via `x-nullable`, however, it did so by appending `None` to the existing `enum` values.
This mutation is probably benign but it could result in some weird behavior.
Fixed to not modify the input value.
> remove mutation of enum values

- tests/core/test_example_schemas.py
- tests/core/test_format_validators.py
Next master build on Travis [should fail](https://travis-ci.org/javabrett/flex/jobs/457318305#L521):
```
E   _pytest.warning_types.RemovedInPytest4Warning: Applying marks directly to parameters is deprecated, please use pytest.param(..., marks=...) instead.
E   For more details, see: https://docs.pytest.org/en/latest/parametrize.html
```
... as `pytest` 4.0 has been released and has some deprecation around `pytest.mark.xfail` API.
Rescued this commit from #209.
> pytest: replaced deprecated pytest.mark.xfail usage

- flex/loading/common/mimetypes.py
RFC7231 (https://tools.ietf.org/html/rfc7231#section-5.3.2)
does not specify that space after ; character is required.
As a matter of fact, in some examples in RFC it provides
examples without space after ; character.
> optional space in mimetype before parameters

- flex/loading/common/mimetypes.py
- tests/loading/schema/test_mimetype_validation.py
> Add test vector for no whitespace after semicolon in mimetype

- .travis.yml
- README.md
It's rather annoying to have all of the actual code tests pass, only for CI to fail due to flake8 complaining.
This PR rearranges the order of tests so Travis executes the flake8 tests first. This should help speed up PRs that pass code tests but fail flake8.
I also update the README to remove the "unmaintained" status of the project, since I'm now the maintainer.
> Move flake8 tests to top first

- flex/_compat.py
- flex/constants.py
- flex/core.py
- flex/datastructures.py
- flex/exceptions.py
- flex/paths.py
- flex/utils.py
- flex/validation/common.py
- flex/validation/schema.py
- tests/core/test_load_source.py
- tests/utils.py
#215 wasn't complete--this addresses the same `DeprecationWarning` everywhere.
> Address all collections.abc DeprecationWarnings

- setup.py
Tests aren't run against Python 3.3
> Remove Python 3.3 classifier

- docs/index.rst
- flex/error_messages.py
"than" is superflous. Fixes #208.
> Fix typo in MINIMUM_AND_MAXIMUM_MESSAGES['invalid']

- flex/loading/common/mimetypes.py
- flex/loading/schema/host.py
- flex/paths.py
Fixes the following:
```
❯ flake8 | rg escape
./flex/paths.py:21:7: W605 invalid escape sequence '\.'
./flex/paths.py:21:13: W605 invalid escape sequence '\.'
./flex/paths.py:22:7: W605 invalid escape sequence '\{'
./flex/paths.py:22:13: W605 invalid escape sequence '\{'
./flex/paths.py:23:7: W605 invalid escape sequence '\}'
./flex/paths.py:23:13: W605 invalid escape sequence '\}'
./flex/paths.py:42:32: W605 invalid escape sequence '\{'
./flex/paths.py:42:36: W605 invalid escape sequence '\}'
./flex/paths.py:56:21: W605 invalid escape sequence '\d'
./flex/loading/common/mimetypes.py:26:11: W605 invalid escape sequence '\.'
./flex/loading/common/mimetypes.py:26:28: W605 invalid escape sequence '\.'
./flex/loading/common/mimetypes.py:29:7: W605 invalid escape sequence '\+' …
```
> Fix invalid escape sequence deprecation warnings
