flex/formats.py
Updated version of flake8 produces some new linting errors.
Moved an import lower in the file.
Travis passes.
=> fix linting errors

.travis.yml, flex/http.py, tests/http/test_request_normalization.py, tests/http/test_response_normalization.py, tox.ini
This is a WIP to add support for tornado request/response normalization.
todo:
Also, here's [a cute picture of a sleeping fox](http://smokingdesigners.com/wp-content/uploads/2012/05/Fox.jpg)!
=> draft tornado request/response support

flex/validation/common.py, tests/validation/parameter/test_unique_items_validation.py
=> serialize values as json before counting.

flex/validation/common.py, flex/validation/schema.py, tests/validation/schema/test_allof_validation.py, tests/validation/schema/test_anyof_validation.py
I'm not sure I'm covering all the cases, here, please have a look and feel free to contribute
=> Implement validation of anyOf and allOf

flex/paths.py, tests/core/test_match_request_path_to_api_path.py, tests/schemas/httpbin.yaml
Fixes #106.
http://imgfave-herokuapp-com.global.ssl.fastly.net/image_cache/1388563321345155.jpg
=> match basePath [closes #106]

flex/http.py, tests/http/test_response_normalization.py, tests/schemas/httpbin.yaml, tests/validation/operation/test_consumes_validation.py, tests/validation/operation/test_parameter_validation.py, tests/validation/request/test_request_content_type_validation.py, tests/validation/request/test_request_path_validation.py, tests/validation/response/test_produces_validation.py, tests/validation/response/test_response_content_type_validation.py, tests/validation/response/test_response_header_validation.py, tests/validation/response/test_response_path_validation.py, tests/validation/response/test_response_status_code_validation.py, tests/validation/response/test_schema_validation.py
=> Fixes issue - response status codes are strings, not ints

flex/loading/schema/info.py, tests/loading/schema/test_info_validation.py
Not going into all details of #77, but small steps make big journeys ;)
IMHO having LicenseObject correctly validated worth a fix.
Thanks!
=> Fix LicenseObject type

flex/core.py, flex/http.py, tests/http/test_request_normalization.py, tests/validation/api_call/test_api_call_validation.py, tox.ini
Hello, I am looking for a way to validate [Falcon](https://falconframework.org/) Request against Swagger schema. If you consider it interesting, I am ready to continue development as I have a couple of ideas to investigate.
=> Support Falcon request validation

flex/http.py
Support for content type with charset value, e.g. 'application/json; charset=utf-8'
=> Support for application/json with encoding

flex/http.py, tests/http/test_request_data_property.py
Support for requests with content type 'x-www-form-urlencoded'
=> Request supports x-www-form-urlencoded content type

flex/http.py
Similar to #128, but for the response.
Probably fixes issue #117.
=> Support for application/json with encoding (response)

flex/validation/response.py, requirements-dev.txt, tests/validation/response/test_response_status_code_validation.py
Fix issue #139 
Also added `flake8` and `coverage` to `requirements-dev.txt`
=> Fix status_code (int) not converted to str - Issue #139

flex/paths.py, tests/core/test_match_request_path_to_api_path.py
This is the pull request for the issue #150.
=> PR for the issue #150

.gitignore
This is generated by tests and should not be committed.
=> Add .cache/ to .gitignore

flex/parameters.py, tests/core/test_parameter_utils.py
Exceptions on the wrong positions.
Thanks
=> Fix wrong exceptions

CHANGELOG, flex/validation/common.py, tests/validation/headers/test_header_type_casting.py
=> Handle collectionFormat multi in parameters

.travis.yml, docs/index.rst, flex/core.py, flex/http.py, tests/http/test_request_normalization.py, tests/http/test_response_normalization.py, tox.ini
=> Add request/response normalizers for flask/werkzeug

flex/loading/definitions/__init__.py, flex/validation/response.py, tests/validation/response/test_response_method_validation.py
=> Response validation fix message for not existing method

CHANGELOG, setup.py
did some version dependency pinning changes so lets make sure everything still works.
=> 6.13.0 release

setup.py
Ref: https://github.com/pipermerriam/flex/commit/009151d970#r28482893
=> deps: fix pinning of click

.travis.yml, setup.py, tox.ini
Added some tox envs for testing compatibility with Python 3.6 and Django 1.11.
=> Test Python 3.6 and Django 1.11

CHANGELOG, setup.py
=> Bump version to 6.14.0 and update CHANGELOG

README.md, flex/constants.py, flex/utils.py
=> Fix misspellings: s/PRIMATIVE/PRIMITIVE/ and s/collission/collision

README.md
=> Use higher-quality badges from badgen

.travis.yml, setup.py, tox.ini
Added some tox envs for testing compatibility with Python 3.7
=> Test Python 3.7

.travis.yml
Travis-CI has added support for ARM64. Added ARM64 job in Travis-CI.
=> Adding Arm64 Travis Support

.travis.yml, setup.py, tox.ini
=> Update testing and support matrix
